-- MySQL Script generated by MySQL Workbench
-- 06/06/17 23:48:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sad2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sad2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sad2` DEFAULT CHARACTER SET utf8 ;
USE `sad2` ;

-- -----------------------------------------------------
-- Table `sad2`.`generalprofile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`generalprofile` (
  `profileID` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `midName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `suffix` VARCHAR(5) NULL DEFAULT NULL,
  `birthdate` DATE NULL DEFAULT NULL,
  `gender` CHAR(1) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `birthplace` VARCHAR(45) NULL DEFAULT NULL,
  `bloodType` CHAR(5) NULL DEFAULT NULL,
  `fatherID` INT NULL,
  `motherID` INT NULL,
  `orgName` VARCHAR(45) NULL DEFAULT NULL,
  `lastModified` DATETIME NULL DEFAULT NULL,
  `userID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`profileID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `sad2`.`generalprofile` ADD UNIQUE personName(firstName, midName, lastName, suffix, birthdate, gender);
-- -----------------------------------------------------
-- Table `sad2`.`application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`application` (
  `profileID` INT(11) NOT NULL,
  `applicationID` INT(11) NOT NULL AUTO_INCREMENT,
  `applicationType` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `userID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`applicationID`, `profileID`),
  INDEX `app_genprof_idx` (`profileID` ASC),
  CONSTRAINT `app_genprof`
    FOREIGN KEY (`profileID`)
    REFERENCES `sad2`.`generalprofile` (`profileID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sad2`.`requirement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`requirement` (
  `requirementID` INT(11) NOT NULL AUTO_INCREMENT,
  `requirementName` VARCHAR(45) NULL DEFAULT NULL,
  `sacramentType` VARCHAR(45) NULL DEFAULT NULL,
  `userID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`requirementID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sad2`.`application_requirement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`application_requirement` (
  `applicationID` INT(11) NOT NULL,
  `requirementID` INT(11) NOT NULL,
  `userID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`applicationID`, `requirementID`),
  INDEX `appReq_app_idx` (`requirementID` ASC),
  CONSTRAINT `appReq_app`
    FOREIGN KEY (`applicationID`)
    REFERENCES `sad2`.`application` (`applicationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `appReq_req`
    FOREIGN KEY (`requirementID`)
    REFERENCES `sad2`.`requirement` (`requirementID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sad2`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`schedule` (
  `scheduleID` INT(11) NOT NULL AUTO_INCREMENT,
  `scheduleType` VARCHAR(45) NULL DEFAULT NULL,
  `startDateTime` DATETIME NULL DEFAULT NULL,
  `endDateTime` DATETIME NULL DEFAULT NULL,
  `details` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `priority` VARCHAR(45) NULL DEFAULT NULL,
  `userID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`scheduleID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sad2`.`minister`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`minister` (
  `minsiterID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `midName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `suffix` VARCHAR(10) NULL,
  `birthdate` DATE NULL,
  `ministryType` VARCHAR(45) NULL,
  `active` BIT NULL,
  `licenseNumber` VARCHAR(45) NULL,
  `expirationDate` DATE NULL,
  `userID` INT NULL,
  `lastModified` DATETIME NULL,
  PRIMARY KEY (`minsiterID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sad2`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`appointment` (
  `appointmentID` INT(11) NOT NULL AUTO_INCREMENT,
  `profileID` INT(11) NOT NULL,
  `ministerID` INT(11) NULL DEFAULT NULL,
  `lastModified` DATETIME NULL DEFAULT NULL,
  `scheduleID` INT(11) NULL DEFAULT NULL,
  `userID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`appointmentID`, `profileID`),
  INDEX `app_gen_idx` (`profileID` ASC),
  INDEX `app_sched_idx` (`scheduleID` ASC),
  INDEX `app_min_idx` (`ministerID` ASC),
  CONSTRAINT `app_gen`
    FOREIGN KEY (`profileID`)
    REFERENCES `sad2`.`generalprofile` (`profileID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `app_sched`
    FOREIGN KEY (`scheduleID`)
    REFERENCES `sad2`.`schedule` (`scheduleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `app_min`
    FOREIGN KEY (`ministerID`)
    REFERENCES `sad2`.`minister` (`minsiterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sad2`.`blooddonationevent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`blooddonationevent` (
  `bloodDonationEventID` INT(11) NOT NULL AUTO_INCREMENT,
  `eventName` VARCHAR(45) NULL DEFAULT NULL,
  `eventDate` DATE NULL DEFAULT NULL,
  `eventStatus` VARCHAR(10) NULL DEFAULT NULL,
  `eventVenue` VARCHAR(45) NULL DEFAULT NULL,
  `eventDetails` VARCHAR(45) NULL DEFAULT NULL,
  `scheduleID` INT(11) NULL DEFAULT NULL,
  `userID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`bloodDonationEventID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sad2`.`blooddonation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`blooddonation` (
  `bloodDonationID` INT(11) NOT NULL AUTO_INCREMENT,
  `profileID` INT(11) NOT NULL,
  `bloodDonationEventID` INT(11) NOT NULL,
  `donationAmount` DOUBLE NULL DEFAULT NULL,
  `userID` INT(11) NULL DEFAULT NULL,
  INDEX `fk_blooddonation_generalprofile1_idx` (`profileID` ASC),
  INDEX `fk_blooddonation_blooddonationevent1_idx` (`bloodDonationEventID` ASC),
  PRIMARY KEY (`bloodDonationID`, `profileID`, `bloodDonationEventID`),
  CONSTRAINT `fk_blooddonation_generalprofile1`
    FOREIGN KEY (`profileID`)
    REFERENCES `sad2`.`generalprofile` (`profileID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blooddonation_blooddonationevent1`
    FOREIGN KEY (`bloodDonationEventID`)
    REFERENCES `sad2`.`blooddonationevent` (`bloodDonationEventID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sad2`.`blooddonationretrieval`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`blooddonationretrieval` (
  `bloodDonationID` INT(11) NOT NULL,
  `claimDate` DATETIME NULL DEFAULT NULL,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `midName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `suffix` VARCHAR(5) NULL DEFAULT NULL,
  `birthdate` DATE NULL DEFAULT NULL,
  `gender` CHAR(1) NULL DEFAULT NULL,
  `userID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`bloodDonationID`),
  CONSTRAINT `bdretrieve_bd`
    FOREIGN KEY (`bloodDonationID`)
    REFERENCES `sad2`.`blooddonation` (`bloodDonationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sad2`.`parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`parent` (
  `parentID` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `midName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `suffix` VARCHAR(5) NULL DEFAULT NULL,
  `birthdate` DATE NULL DEFAULT NULL,
  `gender` CHAR(1) NULL DEFAULT NULL,
  `birthplace` VARCHAR(45) NULL DEFAULT NULL,
  `userID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`parentID`),
  CONSTRAINT `parentID_profileID`
    FOREIGN KEY (`parentID`)
    REFERENCES `sad2`.`generalprofile` (`profileID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sad2`.`sacrament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`sacrament` (
  `sacramentID` INT NOT NULL AUTO_INCREMENT,
  `profileID` INT NOT NULL,
  `ministerID` INT NULL,
  `sponsorID` INT NULL,
  `userID` INT NULL,
  PRIMARY KEY (`sacramentID`, `profileID`),
  INDEX `sac_min_idx` (`ministerID` ASC),
  INDEX `sac_gen_idx` (`profileID` ASC),
  CONSTRAINT `sac_gen`
    FOREIGN KEY (`profileID`)
    REFERENCES `sad2`.`generalprofile` (`profileID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sac_min`
    FOREIGN KEY (`ministerID`)
    REFERENCES `sad2`.`minister` (`minsiterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sad2`.`marriage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`marriage` (
  `sacramentID` INT NOT NULL AUTO_INCREMENT,
  `profileA` INT NULL,
  `profileB` INT NULL,
  `recordNumber` VARCHAR(45) NULL,
  `pageNumber` VARCHAR(4) NULL,
  `registryNumber` VARCHAR(45) NULL,
  `licenseDate` DATE NULL,
  `marriageDate` DATE NULL,
  `lastModified` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  `details` VARCHAR(45) NULL,
  PRIMARY KEY (`sacramentID`),
  CONSTRAINT `marr_sac`
    FOREIGN KEY (`sacramentID`)
    REFERENCES `sad2`.`sacrament` (`sacramentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sad2`.`baptism`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`baptism` (
  `sacramentID` INT NOT NULL AUTO_INCREMENT,
  `recordNumber` VARCHAR(45) NULL,
  `pageNumber` VARCHAR(45) NULL,
  `registryNumber` VARCHAR(45) NULL,
  `baptismDate` DATETIME NULL,
  `lastModified` DATETIME NULL,
  PRIMARY KEY (`sacramentID`),
  CONSTRAINT `bap_sec`
    FOREIGN KEY (`sacramentID`)
    REFERENCES `sad2`.`sacrament` (`sacramentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sad2`.`sponsor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`sponsor` (
  `sponsorID` INT NOT NULL AUTO_INCREMENT,
  `sacramentID` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `middleName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `suffix` VARCHAR(10) NULL,
  `gender` CHAR(1) NULL,
  PRIMARY KEY (`sponsorID`, `sacramentID`),
  INDEX `spon_sac_idx` (`sacramentID` ASC),
  CONSTRAINT `spon_sac`
    FOREIGN KEY (`sacramentID`)
    REFERENCES `sad2`.`sacrament` (`sacramentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sad2`.`confirmation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`confirmation` (
  `sacramentID` INT NOT NULL AUTO_INCREMENT,
  `recordNumber` VARCHAR(45) NULL,
  `pageNumber` VARCHAR(45) NULL,
  `registryNumber` VARCHAR(45) NULL,
  `confirmationDate` DATE NULL,
  `lastModified` DATETIME NULL,
  PRIMARY KEY (`sacramentID`),
  CONSTRAINT `con_sac`
    FOREIGN KEY (`sacramentID`)
    REFERENCES `sad2`.`sacrament` (`sacramentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sad2`.`incometype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`incometype` (
  `incomeTypeID` INT NOT NULL AUTO_INCREMENT,
  `incomeType` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `price` DOUBLE NULL,
  `active` BIT NULL,
  `userID` VARCHAR(45) NULL,
  PRIMARY KEY (`incomeTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sad2`.`income`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`income` (
  `incomeID` INT NOT NULL AUTO_INCREMENT,
  `incomeTypeID` INT NOT NULL,
  `profileID` INT NULL,
  `incomeDescription` VARCHAR(45) NULL,
  `incomeAmount` DOUBLE NULL,
  `incomeDateTime` DATETIME NULL,
  `ORnum` VARCHAR(45) NULL,
  `userID` INT NULL,
  PRIMARY KEY (`incomeID`, `incomeTypeID`),
  INDEX `in_inType_idx` (`incomeTypeID` ASC),
  CONSTRAINT `in_inType`
    FOREIGN KEY (`incomeTypeID`)
    REFERENCES `sad2`.`incometype` (`incomeTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sad2`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`user` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `userType` VARCHAR(45) NULL,
  `active` BIT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB
COMMENT = '				';

ALTER TABLE `sad2`.`user` ADD UNIQUE userAccount(username, password);
-- -----------------------------------------------------
-- Table `sad2`.`cashreleasetype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`cashreleasetype` (
  `cashReleaseTypeID` INT NOT NULL AUTO_INCREMENT,
  `cashReleaseType` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `active` BIT NULL,
  `userID` INT NULL,
  PRIMARY KEY (`cashReleaseTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sad2`.`cashrelease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`cashrelease` (
  `cashReleaseID` INT NOT NULL AUTO_INCREMENT,
  `cashReleaseTypeID` INT NOT NULL,
  `cashReleaseDateTime` DATETIME NULL,
  `remark` VARCHAR(45) NULL,
  `releaseAmount` DOUBLE NULL,
  `userID` INT NULL,
  PRIMARY KEY (`cashReleaseID`, `cashReleaseTypeID`),
  INDEX `cashRel_cashRelType_idx` (`cashReleaseTypeID` ASC),
  CONSTRAINT `cashRel_cashRelType`
    FOREIGN KEY (`cashReleaseTypeID`)
    REFERENCES `sad2`.`cashreleasetype` (`cashReleaseTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sad2`.`baptismlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`baptismlog` (
  `sacramentID` INT NULL,
  `recordNumber` VARCHAR(45) NULL,
  `pageNumber` VARCHAR(45) NULL,
  `registryNumber` VARCHAR(45) NULL,
  `lastModified` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sad2`.`generalprofilelog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`generalprofilelog` (
  `profileID` INT(11) NULL,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `midName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `suffix` VARCHAR(5) NULL DEFAULT NULL,
  `birthdate` DATE NULL DEFAULT NULL,
  `gender` CHAR(1) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `birthplace` VARCHAR(45) NULL DEFAULT NULL,
  `bloodType` CHAR(5) NULL DEFAULT NULL,
  `fatherID` INT NULL,
  `motherID` INT NULL,
  `orgName` VARCHAR(45) NULL DEFAULT NULL,
  `lastModified` DATETIME NULL DEFAULT NULL,
  `userID` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sad2`.`marriagelog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`marriagelog` (
  `sacramentID` INT NULL,
  `profileA` INT NULL,
  `profileB` INT NULL,
  `recordNumber` VARCHAR(45) NULL,
  `pageNumber` VARCHAR(4) NULL,
  `registryNumber` VARCHAR(45) NULL,
  `licenseDate` DATE NULL,
  `marriageDate` DATE NULL,
  `lastModified` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  `details` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sad2`.`confirmationlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`confirmationlog` (
  `sacramentID` INT NULL,
  `recordNumber` VARCHAR(45) NULL,
  `pageNumber` VARCHAR(45) NULL,
  `registryNumber` VARCHAR(45) NULL,
  `confirmationDate` DATE NULL,
  `lastModified` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sad2`.`blooddonationeventlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`blooddonationeventlog` (
  `bloodDonationEventID` INT(11) NULL,
  `eventName` VARCHAR(45) NULL DEFAULT NULL,
  `eventDate` DATE NULL DEFAULT NULL,
  `eventStatus` VARCHAR(10) NULL DEFAULT NULL,
  `eventVenue` VARCHAR(45) NULL DEFAULT NULL,
  `eventDetails` VARCHAR(45) NULL DEFAULT NULL,
  `scheduleID` INT(11) NULL DEFAULT NULL,
  `userID` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sad2`.`blooddonationlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`blooddonationlog` (
  `bloodDonationID` INT(11) NULL,
  `profileID` INT(11) NULL DEFAULT NULL,
  `bloodDonationEventID` INT(11) NULL,
  `donationAmount` DOUBLE NULL DEFAULT NULL,
  `userID` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sad2`.`incomelog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`incomelog` (
  `incomeID` INT NULL,
  `incomeTypeID` INT NULL,
  `profileID` INT NULL,
  `incomeDescription` VARCHAR(45) NULL,
  `incomeAmount` DOUBLE NULL,
  `incomeDateTime` DATETIME NULL,
  `ORnum` VARCHAR(45) NULL,
  `userID` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sad2`.`cashreleaselog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sad2`.`cashreleaselog` (
  `cashReleaseID` INT NULL,
  `cashReleaseTypeID` INT NULL,
  `cashReleaseDateTime` DATETIME NULL,
  `remark` VARCHAR(45) NULL,
  `releaseAmount` DOUBLE NULL,
  `userID` INT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
